# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='machine_learning',
  syntax='proto3',
  serialized_options=b'\n\030io.grpc.machine_learningB\017MachineLearningP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\x12\x10machine_learning\"%\n\x14PredictSalaryRequest\x12\r\n\x05years\x18\x01 \x01(\x05\"\'\n\x15PredictSalaryResponse\x12\x0e\n\x06salary\x18\x01 \x01(\x02\"5\n\x16PredictPurchaseRequest\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\x12\x0e\n\x06salary\x18\x02 \x01(\x02\"+\n\x17PredictPurchaseResponse\x12\x10\n\x08purchase\x18\x01 \x01(\x08\"F\n\x15PredictSegmentRequest\x12\x15\n\rannual_income\x18\x01 \x01(\x02\x12\x16\n\x0espending_score\x18\x02 \x01(\x02\"L\n\x16PredictSegmentResponse\x12\x32\n\x07segment\x18\x01 \x01(\x0e\x32!.machine_learning.CustomerSegment\"#\n!GetOptimalCampaignAdOptionRequest\"0\n\"GetOptimalCampaignAdOptionResponse\x12\n\n\x02\x61\x64\x18\x01 \x01(\x05\"-\n\x1bPredictReviewOutcomeRequest\x12\x0e\n\x06review\x18\x01 \x01(\t\"-\n\x1cPredictReviewOutcomeResponse\x12\r\n\x05liked\x18\x01 \x01(\x08*\x87\x02\n\x0f\x43ustomerSegment\x12\x13\n\x0fUNKNOWN_SEGMENT\x10\x00\x12/\n+MEDIUM_INCOME_MEDIUM_SPENDING_SCORE_SEGMENT\x10\x01\x12*\n&LOW_INCOME_HIGH_SPENDING_SCORE_SEGMENT\x10\x02\x12+\n\'HIGH_INCOME_HIGH_SPENDING_SCORE_SEGMENT\x10\x03\x12)\n%LOW_INCOME_LOW_SPENDING_SCORE_SEGMENT\x10\x04\x12*\n&HIGH_INCOME_LOW_SPENDING_SCORE_SEGMENT\x10\x05\x32\xcb\x04\n\x0fMachineLearning\x12\x62\n\rPredictSalary\x12&.machine_learning.PredictSalaryRequest\x1a\'.machine_learning.PredictSalaryResponse\"\x00\x12h\n\x0fPredictPurchase\x12(.machine_learning.PredictPurchaseRequest\x1a).machine_learning.PredictPurchaseResponse\"\x00\x12\x65\n\x0ePredictSegment\x12\'.machine_learning.PredictSegmentRequest\x1a(.machine_learning.PredictSegmentResponse\"\x00\x12\x89\x01\n\x1aGetOptimalCampaignAdOption\x12\x33.machine_learning.GetOptimalCampaignAdOptionRequest\x1a\x34.machine_learning.GetOptimalCampaignAdOptionResponse\"\x00\x12w\n\x14PredictReviewOutcome\x12-.machine_learning.PredictReviewOutcomeRequest\x1a..machine_learning.PredictReviewOutcomeResponse\"\x00\x42-\n\x18io.grpc.machine_learningB\x0fMachineLearningP\x01\x62\x06proto3'
)

_CUSTOMERSEGMENT = _descriptor.EnumDescriptor(
  name='CustomerSegment',
  full_name='machine_learning.CustomerSegment',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_SEGMENT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM_INCOME_MEDIUM_SPENDING_SCORE_SEGMENT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOW_INCOME_HIGH_SPENDING_SCORE_SEGMENT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HIGH_INCOME_HIGH_SPENDING_SCORE_SEGMENT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOW_INCOME_LOW_SPENDING_SCORE_SEGMENT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HIGH_INCOME_LOW_SPENDING_SCORE_SEGMENT', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=547,
  serialized_end=810,
)
_sym_db.RegisterEnumDescriptor(_CUSTOMERSEGMENT)

CustomerSegment = enum_type_wrapper.EnumTypeWrapper(_CUSTOMERSEGMENT)
UNKNOWN_SEGMENT = 0
MEDIUM_INCOME_MEDIUM_SPENDING_SCORE_SEGMENT = 1
LOW_INCOME_HIGH_SPENDING_SCORE_SEGMENT = 2
HIGH_INCOME_HIGH_SPENDING_SCORE_SEGMENT = 3
LOW_INCOME_LOW_SPENDING_SCORE_SEGMENT = 4
HIGH_INCOME_LOW_SPENDING_SCORE_SEGMENT = 5



_PREDICTSALARYREQUEST = _descriptor.Descriptor(
  name='PredictSalaryRequest',
  full_name='machine_learning.PredictSalaryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='years', full_name='machine_learning.PredictSalaryRequest.years', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=72,
)


_PREDICTSALARYRESPONSE = _descriptor.Descriptor(
  name='PredictSalaryResponse',
  full_name='machine_learning.PredictSalaryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='salary', full_name='machine_learning.PredictSalaryResponse.salary', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=113,
)


_PREDICTPURCHASEREQUEST = _descriptor.Descriptor(
  name='PredictPurchaseRequest',
  full_name='machine_learning.PredictPurchaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='age', full_name='machine_learning.PredictPurchaseRequest.age', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='salary', full_name='machine_learning.PredictPurchaseRequest.salary', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=168,
)


_PREDICTPURCHASERESPONSE = _descriptor.Descriptor(
  name='PredictPurchaseResponse',
  full_name='machine_learning.PredictPurchaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='purchase', full_name='machine_learning.PredictPurchaseResponse.purchase', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=213,
)


_PREDICTSEGMENTREQUEST = _descriptor.Descriptor(
  name='PredictSegmentRequest',
  full_name='machine_learning.PredictSegmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='annual_income', full_name='machine_learning.PredictSegmentRequest.annual_income', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spending_score', full_name='machine_learning.PredictSegmentRequest.spending_score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=285,
)


_PREDICTSEGMENTRESPONSE = _descriptor.Descriptor(
  name='PredictSegmentResponse',
  full_name='machine_learning.PredictSegmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment', full_name='machine_learning.PredictSegmentResponse.segment', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=363,
)


_GETOPTIMALCAMPAIGNADOPTIONREQUEST = _descriptor.Descriptor(
  name='GetOptimalCampaignAdOptionRequest',
  full_name='machine_learning.GetOptimalCampaignAdOptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=400,
)


_GETOPTIMALCAMPAIGNADOPTIONRESPONSE = _descriptor.Descriptor(
  name='GetOptimalCampaignAdOptionResponse',
  full_name='machine_learning.GetOptimalCampaignAdOptionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ad', full_name='machine_learning.GetOptimalCampaignAdOptionResponse.ad', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=450,
)


_PREDICTREVIEWOUTCOMEREQUEST = _descriptor.Descriptor(
  name='PredictReviewOutcomeRequest',
  full_name='machine_learning.PredictReviewOutcomeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='review', full_name='machine_learning.PredictReviewOutcomeRequest.review', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=497,
)


_PREDICTREVIEWOUTCOMERESPONSE = _descriptor.Descriptor(
  name='PredictReviewOutcomeResponse',
  full_name='machine_learning.PredictReviewOutcomeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='liked', full_name='machine_learning.PredictReviewOutcomeResponse.liked', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=544,
)

_PREDICTSEGMENTRESPONSE.fields_by_name['segment'].enum_type = _CUSTOMERSEGMENT
DESCRIPTOR.message_types_by_name['PredictSalaryRequest'] = _PREDICTSALARYREQUEST
DESCRIPTOR.message_types_by_name['PredictSalaryResponse'] = _PREDICTSALARYRESPONSE
DESCRIPTOR.message_types_by_name['PredictPurchaseRequest'] = _PREDICTPURCHASEREQUEST
DESCRIPTOR.message_types_by_name['PredictPurchaseResponse'] = _PREDICTPURCHASERESPONSE
DESCRIPTOR.message_types_by_name['PredictSegmentRequest'] = _PREDICTSEGMENTREQUEST
DESCRIPTOR.message_types_by_name['PredictSegmentResponse'] = _PREDICTSEGMENTRESPONSE
DESCRIPTOR.message_types_by_name['GetOptimalCampaignAdOptionRequest'] = _GETOPTIMALCAMPAIGNADOPTIONREQUEST
DESCRIPTOR.message_types_by_name['GetOptimalCampaignAdOptionResponse'] = _GETOPTIMALCAMPAIGNADOPTIONRESPONSE
DESCRIPTOR.message_types_by_name['PredictReviewOutcomeRequest'] = _PREDICTREVIEWOUTCOMEREQUEST
DESCRIPTOR.message_types_by_name['PredictReviewOutcomeResponse'] = _PREDICTREVIEWOUTCOMERESPONSE
DESCRIPTOR.enum_types_by_name['CustomerSegment'] = _CUSTOMERSEGMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PredictSalaryRequest = _reflection.GeneratedProtocolMessageType('PredictSalaryRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTSALARYREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:machine_learning.PredictSalaryRequest)
  })
_sym_db.RegisterMessage(PredictSalaryRequest)

PredictSalaryResponse = _reflection.GeneratedProtocolMessageType('PredictSalaryResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTSALARYRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:machine_learning.PredictSalaryResponse)
  })
_sym_db.RegisterMessage(PredictSalaryResponse)

PredictPurchaseRequest = _reflection.GeneratedProtocolMessageType('PredictPurchaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTPURCHASEREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:machine_learning.PredictPurchaseRequest)
  })
_sym_db.RegisterMessage(PredictPurchaseRequest)

PredictPurchaseResponse = _reflection.GeneratedProtocolMessageType('PredictPurchaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTPURCHASERESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:machine_learning.PredictPurchaseResponse)
  })
_sym_db.RegisterMessage(PredictPurchaseResponse)

PredictSegmentRequest = _reflection.GeneratedProtocolMessageType('PredictSegmentRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTSEGMENTREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:machine_learning.PredictSegmentRequest)
  })
_sym_db.RegisterMessage(PredictSegmentRequest)

PredictSegmentResponse = _reflection.GeneratedProtocolMessageType('PredictSegmentResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTSEGMENTRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:machine_learning.PredictSegmentResponse)
  })
_sym_db.RegisterMessage(PredictSegmentResponse)

GetOptimalCampaignAdOptionRequest = _reflection.GeneratedProtocolMessageType('GetOptimalCampaignAdOptionRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETOPTIMALCAMPAIGNADOPTIONREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:machine_learning.GetOptimalCampaignAdOptionRequest)
  })
_sym_db.RegisterMessage(GetOptimalCampaignAdOptionRequest)

GetOptimalCampaignAdOptionResponse = _reflection.GeneratedProtocolMessageType('GetOptimalCampaignAdOptionResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETOPTIMALCAMPAIGNADOPTIONRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:machine_learning.GetOptimalCampaignAdOptionResponse)
  })
_sym_db.RegisterMessage(GetOptimalCampaignAdOptionResponse)

PredictReviewOutcomeRequest = _reflection.GeneratedProtocolMessageType('PredictReviewOutcomeRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTREVIEWOUTCOMEREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:machine_learning.PredictReviewOutcomeRequest)
  })
_sym_db.RegisterMessage(PredictReviewOutcomeRequest)

PredictReviewOutcomeResponse = _reflection.GeneratedProtocolMessageType('PredictReviewOutcomeResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTREVIEWOUTCOMERESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:machine_learning.PredictReviewOutcomeResponse)
  })
_sym_db.RegisterMessage(PredictReviewOutcomeResponse)


DESCRIPTOR._options = None

_MACHINELEARNING = _descriptor.ServiceDescriptor(
  name='MachineLearning',
  full_name='machine_learning.MachineLearning',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=813,
  serialized_end=1400,
  methods=[
  _descriptor.MethodDescriptor(
    name='PredictSalary',
    full_name='machine_learning.MachineLearning.PredictSalary',
    index=0,
    containing_service=None,
    input_type=_PREDICTSALARYREQUEST,
    output_type=_PREDICTSALARYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PredictPurchase',
    full_name='machine_learning.MachineLearning.PredictPurchase',
    index=1,
    containing_service=None,
    input_type=_PREDICTPURCHASEREQUEST,
    output_type=_PREDICTPURCHASERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PredictSegment',
    full_name='machine_learning.MachineLearning.PredictSegment',
    index=2,
    containing_service=None,
    input_type=_PREDICTSEGMENTREQUEST,
    output_type=_PREDICTSEGMENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOptimalCampaignAdOption',
    full_name='machine_learning.MachineLearning.GetOptimalCampaignAdOption',
    index=3,
    containing_service=None,
    input_type=_GETOPTIMALCAMPAIGNADOPTIONREQUEST,
    output_type=_GETOPTIMALCAMPAIGNADOPTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PredictReviewOutcome',
    full_name='machine_learning.MachineLearning.PredictReviewOutcome',
    index=4,
    containing_service=None,
    input_type=_PREDICTREVIEWOUTCOMEREQUEST,
    output_type=_PREDICTREVIEWOUTCOMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MACHINELEARNING)

DESCRIPTOR.services_by_name['MachineLearning'] = _MACHINELEARNING

# @@protoc_insertion_point(module_scope)
